# version: '3.8'
# services:
#   postgres:
#     image: postgres:14
#     environment:
#       POSTGRES_PASSWORD: yourpassword
#       POSTGRES_DB: uptime_db
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   app:  # Your Spring Boot app
#     build: .  # Looks for Dockerfile in the current directory
#     ports:
#       - "8080:8080"
#     depends_on:
#       - postgres
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/uptime_db
#       SPRING_DATASOURCE_USERNAME: postgres
#       SPRING_DATASOURCE_PASSWORD: yourpassword

# volumes:
#   postgres_data:

version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ajinendra05  # Changed username
      POSTGRES_PASSWORD: SpringBootPassword  # Changed password
      POSTGRES_DB: uptime_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/uptime_db
      SPRING_DATASOURCE_USERNAME: ajinendra05  # Updated username
      SPRING_DATASOURCE_PASSWORD: SpringBootPassword  # Updated password
      SPRING_JPA_HIBERNATE_DDL-AUTO: update

volumes:
  postgres_data: