
version: "3.8"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: BFaNVfwjYHeYPuxMYRrkfLqxWhIxyqiQ 
      POSTGRES_DB: uptime_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres.railway.internal:5432/railway
      SPRING_DATASOURCE_USERNAME: postgres 
      SPRING_DATASOURCE_PASSWORD: BFaNVfwjYHeYPuxMYRrkfLqxWhIxyqiQ 
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  postgres_data:
#   When running through mvn spring-boot:run, use localhost

# When running in Docker container, use postgres as hostname

# You can't mix these approaches
