spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: BFaNVfwjYHeYPuxMYRrkfLqxWhIxyqiQ
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ajinendra2015@gmail.com
    password: mieb ctec rjej zagz
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    to: ajinendra2002@example.com
